#
type=video
name=Ch-3
thumb=http://www.one2hd.com/images/live_logo/195.png
URL=http://thaiiptv.dyndns.tv:1936/live_sv1/DVBT-CH3.stream/playlist.m3u8
#
type=video
name=Ch-5
thumb=http://www.one2hd.com/images/live_logo/57.png
URL=http://thaiiptv.dyndns.tv:1936/live_sv1/DVBT-CH5.stream/playlist.m3u8
#
type=video
name=Ch-7
thumb=http://www.one2hd.com/images/live_logo/98.png
URL=http://thaiiptv.dyndns.tv:1936/live_sv1/DVBT-CH7.stream/playlist.m3u8
#
type=video
name=Ch-9
thumb=http://www.one2hd.com/images/live_logo/58.png
URL=http://thaiiptv.dyndns.tv:1936/live_sv1/DVBT-CH9.stream/playlist.m3u8
#
type=video
name=NBT
thumb=http://www.one2hd.com/images/live_logo/137.png?
URL=http://thaiiptv.dyndns.tv:1936/live_sv1/DVBT-NBT.stream/playlist.m3u8
#
type=video
name=TPBS (HD)
thumb=http://www.one2hd.com/images/live_logo/59.png
URL=http://thaiiptv.dyndns.tv:1936/live_sv1/TPBS.stream/playlist.m3u8
#
